# Generated by Django 2.0 on 2017-12-20 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercadopublico_api', '0002_auto_20171220_2335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comprapublica',
            old_name='state',
            new_name='state_name',
        ),
    ]
