# Generated by Django 2.0 on 2017-12-23 16:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mercadopublico_api', '0005_auto_20171223_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50)),
                ('isLicitacion', models.BooleanField()),
                ('isList', models.BooleanField()),
                ('request', models.CharField(max_length=200)),
                ('response', models.TextField()),
                ('date_ini', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
