# Generated by Django 2.0 on 2017-12-23 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercadopublico_api', '0006_apiresponse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apiresponse',
            old_name='isLicitacion',
            new_name='is_licitacion',
        ),
        migrations.RenameField(
            model_name='apiresponse',
            old_name='isList',
            new_name='is_list',
        ),
    ]
