# Generated by Django 2.0 on 2017-12-28 16:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mercadopublico_api', '0007_auto_20171223_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50)),
                ('is_licitacion', models.BooleanField()),
                ('response', models.TextField()),
                ('date_ini', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='APIList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('is_licitacion', models.BooleanField()),
                ('response', models.TextField()),
                ('date_ini', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='APIResponse',
        ),
    ]
